dist: bionic
group: travis_latest
language: cpp
os:
  - linux

compiler:
  - gcc

env:
  matrix:
    - CPP11=1
    - CPP11=0
  global:
    - ACE_ROOT=$TRAVIS_BUILD_DIR/ext/ATCD/ACE
    - MPC_ROOT=$TRAVIS_BUILD_DIR/ext/MPC
    - XSC_ROOT=$TRAVIS_BUILD_DIR
    - LD_LIBRARY_PATH=$ACE_ROOT/lib:$LD_LIBRARY_PATH

addons:
  apt:
    packages:
      - libssl-dev
      - libxerces-c-dev
      - libboost-all-dev

before_install:
  - mkdir ext
  - cd ext && git clone --depth 1 git://github.com/DOCGroup/MPC.git
  - git clone --depth 1 git://github.com/DOCGroup/ACE_TAO.git ATCD
  - cd ..

branches:
  only:
    - master

before_script:
  - export
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then echo -e "#include \"ace/config-linux.h\"" >> $ACE_ROOT/ace/config.h; fi
  - echo -e "boost=1\nxsc=1\nxerces3=1\n" >> $ACE_ROOT/include/makeinclude/platform_macros.GNU
  - if [ "$CPP11" == "1" ]; then echo -e "c++11=1\n" >> $ACE_ROOT/include/makeinclude/platform_macros.GNU; fi
  - echo -e "boost=1\nxerces3=1\nxsc=1\n" >> $ACE_ROOT/bin/MakeProjectCreator/config/default.features
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      if [ "$CXX" == "g++" ]; then
        echo -e "include \$(ACE_ROOT)/include/makeinclude/platform_linux.GNU" >> $ACE_ROOT/include/makeinclude/platform_macros.GNU;
      else
        echo -e "include \$(ACE_ROOT)/include/makeinclude/platform_linux_clang.GNU" >> $ACE_ROOT/include/makeinclude/platform_macros.GNU;
      fi
    fi
  - cat $ACE_ROOT/bin/MakeProjectCreator/config/default.features
  - cat $ACE_ROOT/ace/config.h
  - cat $ACE_ROOT/include/makeinclude/platform_macros.GNU
  - if [[ "${COMPILER}" != "" ]]; then export CXX=${COMPILER}; fi

script:
  - perl $ACE_ROOT/bin/mwc.pl -type gnuace -workers 2 XSC.mwc
  - make -j 6
